version: '3'
services:
  app1:
    build:
      context: ./03.fp-refactor
      dockerfile: Dockerfile
    ports:
      - "5051:5050"
    networks:
      - mynetwork
    volumes:
      - ./03.fp-refactor/serviceAccountKey.json:/app/serviceAccountKey.json
      - ./05.ip-register:/app/05.ip-register  # Mount thư mục chứa registered_ips.json vào app1
    environment:
      - IP_REGISTER_API=${IP_REGISTER_API}  # Sử dụng biến từ file .env
    restart: always

  app2:
    build:
      context: ./05.ip-register
      dockerfile: Dockerfile
    ports:
      - "5052:5050"
    networks:
      - mynetwork
    volumes:
      - ./05.ip-register/serviceAccountKey.json:/app/serviceAccountKey.json
      - ./05.ip-register:/app/05.ip-register  # Mount thư mục chứa registered_ips.json vào app2
    environment:
      IP_REGISTER_API: "http://35.229.225.169:5050/get_ips"  # Truyền biến môi trường IP_REGISTER_API
    restart: always

  app3:
    build:
      context: ./04.image-detector
      dockerfile: Dockerfile
    ports:
      - "5053:5050"
    networks:
      - mynetwork
    volumes:
      - ./04.image-detector/serviceAccountKey.json:/app/serviceAccountKey.json
      - ./04.image-detector/model:/app/model
    environment:
      IP_REGISTER_API: "http://35.229.225.169:5050/get_ips"  # Truyền biến môi trường IP_REGISTER_API
    restart: always

networks:
  mynetwork:
    driver: bridge
